<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Yotpo\SmsBump\ViewModel\SyncForms;

/***
 * @var $block Template
 * @var $syncFormsViewModel SyncForms
 * @var Escaper $escaper
 */

$syncFormsViewModel = $block->getSyncFormsResponse();
$responseData = $syncFormsViewModel->getSubscriptionData();
?>
<?php if ($responseData): ?>
    <?php foreach ($responseData as $data):?>
        <script type="text/javascript" charset="utf-8" async data-requirecontext="_"
                data-requiremodule="text" src="<?= $escaper->escapeHtml($data['script_source']) ?>">
        </script>
    <?php endforeach; ?>
<?php endif; ?>
