<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Yotpo\SmsBump\ViewModel\SyncForms;

/***
 * @var $block Template
 * @var $syncFormsViewModel SyncForms
 * @var Escaper $escaper
 */

$syncFormsViewModel = $block->getSyncFormsResponse();
$responseData = $syncFormsViewModel->getSubscriptionData();
$escaper = $escaper ?? $block;
?>
<?php if ($responseData): ?>
    <?php foreach ($responseData as $data):?>
        <script>
            require(['<?= $escaper->escapeHtml($data['script_source'])?>'], function() {
                require(['<?= 'SMSBumpForm_'.$escaper->escapeHtml($data['form_id']) ?>']);
            });
        </script>
    <?php endforeach; ?>
<?php endif; ?>
