<?php
/* @var $block SyncFormsButton */

use Magento\Framework\Escaper;
use Yotpo\SmsBump\Block\Adminhtml\System\Config\SyncFormsButton;

/* @var Escaper $escaper*/
$escaper = $escaper ?? $block;
?>

<script>
    require([
        'jquery',
        'prototype',
        'mage/translate'
    ], function($){
        $successDiv = $('#sync_forms_message_success');
        $errorDiv = $('#sync_forms_message_error');
        var currentStore = <?= $escaper->escapeHtml($block->getStoreScope()) ?>;
        var currentWebsite = <?= $escaper->escapeHtml($block->getWebsiteScope()) ?>;
        var message = '';
        var failureMessage = 'Store not found.';
        $('#yotpo_sync_forms_btn').click(function () {
            new Ajax.Request('<?= $escaper->escapeHtml($block->getAjaxUrl()) ?>', {
                asynchronous:   true,
                showLoader: true,
                parameters:{
                    store: currentStore,
                    website: currentWebsite
                },
                onSuccess: function(response) {
                    var respStatus = JSON.parse(response.responseText);
                    var status = respStatus.status;
                    console.log(status);
                    if (status == 0) {
                        message = failureMessage;
                    }
                    if (currentStore === 0 && currentWebsite === 0) {
                        if (status == 1) {
                            message = 'Subscription forms are synced successfully for all stores.';
                        }
                    } else if (currentStore !== 0) {
                        if (status == 1) {
                            message = 'Subscription forms are synced successfully for the store '
                                + currentStore;
                        }
                    } else if (currentWebsite !== 0) {
                        if (status == 1) {
                            message = 'Subscription forms are synced successfully for all stores under website '
                                + currentWebsite;
                        }
                    }
                    if (status == 1) {
                        $successDiv.text($.mage.__(message));
                        $errorDiv.hide();
                        $successDiv.show();
                    } else {
                        $errorDiv.text($.mage.__(failureMessage));
                        $successDiv.hide();
                        $errorDiv.show();
                    }
                },
                onError: function() {
                    $successDiv.hide();
                    $errorDiv.show();
                    $errorDiv.text($.mage.__(failureMessage));
                },
            });
        });

    });
</script>

<?= $block->getButtonHtml() ?>
<div id="sync_forms_message_success" class="message message-success" style="display: none;"></div>
<div id="sync_forms_message_error" class="message message-error" style="display: none;"></div>
