<?php
/**
 * Create account form template
 */
use Yotpo\SmsBump\Block\Form\Renderer\Checkbox;
use Magento\Framework\Escaper;

/* @var $block Checkbox */
/* @var $escaper Escaper */
$escaper = $escaper ?? $block;
$isYotpoSignUpEnabled = $block->isSignUpEnabled();
if ($isYotpoSignUpEnabled) {
    $data = $block->getConfigData();
}
$parent = $block->getParentBlock();
?>
<?php
$fieldCssClass = 'field field-yotpo_accepts_sms_marketing';
$checked = $block->getIsChecked();
?>
<?php if ($isYotpoSignUpEnabled && $data['customAttribute'] == 'yotpo_accepts_sms_marketing'): ?>
    <div class="<?= /* @noEscape */ $fieldCssClass ?>">
        <div class="control">
            <input
                type="checkbox" <?php if ($checked): ?> checked="checked"<?php endif; ?>
                id="yotpo_accepts_sms_marketing"
                name="yotpo_accepts_sms_marketing"
                title="<?= $escaper->escapeHtmlAttr($data['boxHeading']) ?>"
                value="1"
                <?php if ($block->getValue()): ?> checked="checked"<?php endif; ?>
                <?php if ($block->getHtmlClass()): ?>
                    class="select <?= /* @noEscape */ $block->getHtmlClass() ?>"
                <?php endif;?>
            />
            <label class="label" for="yotpo_accepts_sms_marketing">
                <span><?= $escaper->escapeHtml($data['boxHeading']) ?></span></label>
            <?php if ($_message = $data['description']): ?>
                <div class="message"><?= /* @noEscape */ $_message ?></div>
            <?php endif; ?>
            <?php if ($_message = $data['message']): ?>
                <div class="message"><?= /* @noEscape */ $_message ?>
                    <a target="_blank" href="<?= $escaper->escapeUrl($block->getUrl($data['privacyPolicyUrl'])) ?>">
                        <?= $escaper->escapeHtml($data['privacyPolicyText']) ?>
                    </a>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
